# Generated by Django 5.1.6 on 2025-03-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_menu_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
